services:
  blue-web: &web
    container_name: blue-web
    image: ${APP_NAME}:${TAG}
    # ports:
    #   - 127.0.0.1:${APP_PORT}:${APP_PORT}
    # https://www.baeldung.com/ops/docker-compose-expose-vs-ports
    expose:
      - ${APP_PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=PathPrefix(`/`)"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.middlewares.test-retry.retry.attempts=5"
      - "traefik.http.middlewares.test-retry.retry.initialinterval=200ms"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
      - "traefik.http.services.web.loadbalancer.healthCheck.path=/${HEALTH_ROUTE}"
      - "traefik.http.services.web.loadbalancer.healthCheck.interval=10s"
      - "traefik.http.services.web.loadbalancer.healthCheck.timeout=1s"
    restart: always
    env_file:
      - ./app.env
    logging:
      driver: fluentd
      options:
        tag: ${APP_NAME}
    networks:
      - webgateway

  green-web:
    <<: *web
    container_name: green-web

networks:
  webgateway:
    name: global_webgateway
    external: true
