---
- name: Configure docker
  hosts: webservers,monitor
  # become: true
  tasks:
    - name: Install docker dependencies
      ansible.builtin.apt:
        name: '{{ item }}'
        state: present
        update_cache: true
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - pip
        - docker-compose
      become: true

    - name: Install bottle python package
      ansible.builtin.pip:
        name: docker
      become: true

    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: true

    - name: Add Docker's official APT repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present
      become: true

    - name: Install Docker
      ansible.builtin.apt:
        name: docker-ce
        state: present
    #     update_cache: true
      become: true

    - name: Create fluent bit config
      ansible.builtin.template:
        src: configs/fluent-bit.conf.j2
        dest: ~/fluent-bit.conf
        mode: '0644'

    - name: Copy traefik config
      ansible.builtin.copy:
        src: ./configs/traefik.yml
        dest: ~/traefik.yml
        mode: '0644'

    - name: Copy docker compose file with global services
      ansible.builtin.copy:
        src: ./docker-compose.global.yml
        dest: ~/docker-compose.global.yml
        mode: '0644'

    - name: Startup global docker container
      ansible.builtin.command:
        cmd: sudo docker compose --project-name=global --file docker-compose.global.yml up --detach
        chdir: ~
      register: startup_output # <- Registers the command output.
      changed_when: startup_output.rc != 0 # <- Uses the return code to define when the task has changed.

    - name: Startup container output
      ansible.builtin.debug:
        var: startup_output

    - name: Copy docker compose file app
      ansible.builtin.copy:
        src: ./docker-compose.yml
        dest: ~/docker-compose.yml
        mode: '0644'
    - name: Copy deploy script
      ansible.builtin.copy:
        src: ./blue-green-deploy.sh
        dest: ~/blue-green-deploy.sh
        mode: '0644'
